language:
  version: 1.6
  files:
    - config.nims
    - "**/*.nim"
    - "**/*.nimble"
    - "**/*.cfg"
  engines:
    default:
      command: /usr/src/app/server

framework:
  engines:
    - default
