language:
  version: 8.1

  engines:
    reactphp:
      bootstreap:
        - mkdir -p var/cache && chmod 777 var/cache
        - mkdir -p var/log && chmod 777 var/log

      command: bin/console server:run --quiet

framework:
  website: antidotfw.io
  github: antidot-framework/react-framework
  version: 1.0

  files:
    - "**/*.php"
    - composer.json
    - bin/console
    - "**/*.prod.yaml"

  engines:
    - reactphp
